<!-- ============== -->
		<!-- Footer section -->
		<!-- ============== -->
		
		<footer>
			<div class="container" style="margin-right:80px">
				<section class="row foot">
					<article class="span3">
						<strong>Liens Utiles</strong>
						<ul>
							<li><a href="#">A Propos</a></li>
							<li><a href="contact.php">Contactez-nous</a></li>
						</ul>
					</article>
					<article class="span3">
						<strong>Réseaux Sociaux</strong>
						<div id="reseau">
							<div class="social-icons">
  <ul>
<li class="twitter">
<a href="#" target="_blank">Twitter</a>
</li>

<li class="facebook">
<a href="#" target="_blank">Facebook</a>
</li>
<li class="googleplus">
<a href="#" target="_blank">Google +r</a>
</li>
<li class="rss" >
<a href="#" target="_blank">RSS Feed</a>
</li>

</ul>
</div>	
						</div>
					</article>
					<article class="span3">
						<strong>Newsletter</strong>
						<div>
							<form class="form-inline">
							<input class="input-medium" type="text" placeholder="Email address">
							<button class="btn"><i class="icon-direction"></i></button>
							</form>
						</div>
						<address class="row-fluid">
							<div class="pull-left clabel"><i class="icon-location"></i></div>
							<div class="pull-left cdata">1234 Agdal,Rabat Maroc</div>
						</address>
						<address class="row-fluid">
							<div class="pull-left clabel"><i class="icon-phone"></i></div>
							<div class="pull-left cdata">+2120673416058</div>
						</address>
						<address class="row-fluid">
							<div class="pull-left clabel"><i class="icon-mail"></i></div>
							<div class="pull-left cdata"><a href="#">Contact@Ochocoshop.com</a></div>
						</address>
							
					</article>
				</section>

			</div>
			
		
				<section class="row-fluid social">
					<div class="container">
					<div class="pull-left" style="text-align: center">&copy; 2013 Ochoco Shop</div>
					
					</div>
				</section>
			
		</footer>
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="js/jquery.tweet.js"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"></script>
	<script type="text/javascript" src="js/shop.js"></script>
	<script type="text/javascript" src="js/script.js"></script>
	
	</body>
</html>